### ISSUE TITLE
Support for `setup.py`/`setup.cfg` dependencies

### ISSUE THREAD

**Issue by 37b** [CycloneDX/cyclonedx-python#250]
Is it on the roadmap to support the `install_dependencies` set in `setup.py`? It would mean fewer steps from project to bom.xml for projects that utilize a `setup.py` file.

**Comment by jkowalleck** [comment]
@37b do you mean setuptools' `install_requires` ?

**Comment by 37b** [comment]
Yes. Sorry I have been busy.

**Comment by jkowalleck** [comment]
@37b  Could you help us understand the user story?

lets say via `install_requires` we might find a situation like the following: 
```
install_requires =
    typing-extensions >= 3.7.4 ; python_version < '3.8'
    ruamel.yaml >= 0.16
    yamale >= 3.0
    werkzeug >= 1.0 , < 2.0
    mako >= 1.1
    setuptools >= 41.0
    click >= 7.1 , < 8.0
```

and lets say the packae itself was not installed, yet.
this would mean the python env would not have any version of the requirements installed.
could you describe how the process could handle this environment to generate an BOM?

**Comment by jkowalleck** [comment]
had a chat with @37b andhe described the feature the following: 
create a SBOM from a package without freezing the package.

current process: 
1. switch to a target(production/...) environment
1. run pip install <my-project> in that environment
1. then run `pip freeze > requirements.txt` on exactly the same environment.
1. take this `requirements.txt` to be analyzed from _cyclonedx-python_ with the `-r` flag

process after the feature was inplemented
1. switch to a target(production/...) environment
1. run _cyclonedx-python_ directly in the package, to analyze requirements.

**Comment by jkowalleck** [comment]
@37b if you need a `requirements.txt` without installation, 
you can use `pip-compile` from [pip-tools](https://pypi.org/project/pip-tools/).

**Comment by madpah** [comment]
Thanks @jkowalleck for connecting with @37b to get a clear ask for this feature request.

I also agree with your points - reading a list of required dependencies from `setup.cfg`, requirements.txt or any other "list" is at best considered a recipe - it is very unlikely to reflect the actual dependencies installed for numerous reasons - some of which you've already covered.

I have two opposing views on the suitability of this Feature Request:

**AGAINST** Easily producing a BOM from a manifest or "recipe" can lead to a false sense of accuracy/security - we might call this "tick boxing" - you produce a BOM, but the contents are not what you actually require - it will most likely be inaccurate and likely also to be missing dependencies.

**FOR** Given my point against this idea, it should also be called out that this risk essentially already exists (generically) due to how many developers manage their dependencies in Python. `cyclonedx-python` already supports easy BOM generation from a `requirements.txt` file, and not all developers will have a `requirements.txt` that is generated from `pip freeze` after they have installed their dependencies.

Thoughts @jkowalleck / @37b ?

**Comment by 37b** [comment]
The use case I had was to basically check the dependencies on my project before I published it out to our private PyPI. I have moved to `poetry` and have been building BOMs against the `poetry.lock` file to the same effect. 

Basically in this case BOM would say what the app _should_ have, not what it _does_ have in a specific environment.

**Comment by jkowalleck** [comment]
i still do not see any use case, which just means i would not implement the feature myself.
If somebody in the community implements it properly, i would be okay with it. 
----

just to repeat myself: 

Before merging the feature into the product,  I would love to read a concept paper first and I would want to see proper documentation of the feature in the  [docs](https://github.com/CycloneDX/cyclonedx-python/tree/master/docs).

Adding such a feature would enable a "wrong use" of cyclonedx-python.
From existing feature requests, discussions and so on, I already got insights that people do not read the documentation properly, when they just apply any "requirements.txt"... having yet another non-evidence-based bom generator in the official implementation feels bad.

**Comment by 37b** [comment]
As I said I ended up using cdxgen against the poetry.lock for my use case. No need for this enhancement.
